# Generated by Django 3.2.4 on 2021-06-08 11:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('#1', 'Data Analytics'), ('#2', 'Services Analytics'), ('#3', 'Voice Analytics'), ('#4', 'Queue Stats'), ('#5', 'Voice Stats'), ('#6', 'Video Stats'), ('#7', 'Smart Access'), ('#8', 'Diagrams')], max_length=23),
        ),
    ]
